name: colicoli_todo
description: A TODO app assignment.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.4
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  branding: assets/images/splash.png
  color_dark: "#121212"
  android_12:
    image: assets/images/splash.png
    icon_background_color: "#ffffff"



  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Qanelas
      fonts:
        - asset: assets/fonts/QANELASSOFTREGULAR.OTF
          weight: 400
        - asset: assets/fonts/QANELASSOFTLIGHT.OTF
          weight: 200
        - asset: assets/fonts/QANELASSOFTMEDIUM.OTF
          weight: 600
        - asset: assets/fonts/QANELASSOFTBOLD.OTF
          weight: 900
